# KalixMOTD Configuration
# Ultra profesyonel MOTD plugin for Minecraft 1.8-1.21

# Plugin ayarları
settings:
  # Debug modu
  debug: false
  # Otomatik güncelleme kontrolü
  check-updates: true
  # PlaceholderAPI desteği
  placeholderapi-support: true
  # Vault desteği
  vault-support: true

# MOTD ayarları
motd:
  # Ana MOTD mesajları
  messages:
    line1: "§6§lKalixMOTD §8» §fHoş geldiniz!"
    line2: "§7Sunucu sürümü: §a1.8-1.21"
  
  # Rastgele MOTD mesajları (opsiyonel)
  random:
    enabled: true
    interval: 30 # saniye
    messages:
      - line1: "§6§lKalixMOTD §8» §fUltra profesyonel MOTD!"
        line2: "§7Desteklenen sürümler: §a1.8-1.21"
      - line1: "§6§lKalixMOTD §8» §fEn iyi MOTD deneyimi!"
        line2: "§7Özelleştirilebilir ve güçlü"
      - line1: "§6§lKalixMOTD §8» §fModern ve şık tasarım!"
        line2: "§7Tüm Minecraft sürümlerini destekler"
  
  # Hover mesajları (1.16+)
  hover:
    enabled: true
    messages:
      - "§6§lKalixMOTD §8» §fUltra profesyonel MOTD plugin"
      - "§7Desteklenen sürümler: §a1.8-1.21"
      - "§7Özellikler: §aRastgele MOTD, Hover, Click"
      - "§7Yazar: §aKalix"
  
  # Click mesajları (1.16+)
  click:
    enabled: true
    type: "OPEN_URL" # OPEN_URL, RUN_COMMAND, SUGGEST_COMMAND
    value: "https://github.com/kalix/KalixMOTD"

# Sunucu listesi ayarları
server-list:
  # Oyuncu sayısı gösterimi
  player-count:
    enabled: true
    format: "§a{online}§7/§c{max}"
    fake-online: false
    fake-max: false
  
  # Sunucu ikonu
  icon:
    enabled: true
    path: "server-icon.png"
  
  # Sunucu açıklaması
  description:
    enabled: true
    format: "§6§lKalixMOTD\n§7Ultra profesyonel MOTD plugin"

# Özel mesajlar
messages:
  prefix: "§6§l[KalixMOTD] §r"
  reload: "§aPlugin başarıyla yeniden yüklendi!"
  set: "§aMOTD başarıyla güncellendi!"
  no-permission: "§cBu işlem için yetkiniz yok!"
  invalid-command: "§cGeçersiz komut! Kullanım: §f{usage}"
  info:
    - "§6§lKalixMOTD Bilgileri"
    - "§7Sürüm: §a{version}"
    - "§7Yazar: §aKalix"
    - "§7Desteklenen sürümler: §a1.8-1.21"
    - "§7API Sürümü: §a1.13"

# PlaceholderAPI entegrasyonu
placeholders:
  # Özel placeholder'lar
  custom:
    server_name: "KalixMOTD"
    server_version: "1.8-1.21"
    plugin_version: "{version}"
  
  # Vault placeholder'ları
  vault:
    balance: true
    group: true
    prefix: true
    suffix: true

# Performans ayarları
performance:
  # Cache ayarları
  cache:
    enabled: true
    duration: 300 # 5 dakika
  
  # Async işlemler
  async:
    enabled: true
    thread-pool-size: 2

# Gelişmiş özellikler
advanced:
  # JSON MOTD desteği (1.16+)
  json-support: true
  
  # Gradient renk desteği (1.16+)
  gradient-support: true
  
  # Hex renk desteği (1.16+)
  hex-support: true
  
  # MiniMessage desteği (1.16+)
  minimessage-support: false
  
  # Legacy renk desteği (1.8-1.15)
  legacy-support: true

# Log ayarları
logging:
  enabled: true
  level: "INFO" # DEBUG, INFO, WARN, ERROR
  file: "logs/kalixmotd.log"
  max-size: "10MB"
  max-files: 5